### ISSUE TITLE
How can I load external assets before my tests run?

### ISSUE THREAD

**Issue by SaraRavasio** [dferber90/jsdom-screenshot#32]
Hello,
I was trying to add some snapshot tests in my design system repo, and I stumbled upon a problem:
I have to load some internal assets (fonts and icons) that are hosted in a second "assets" repository, accessible via URL, but I can't seem to find a way to load them before my tests run.

This is the snapshot of a button with an icon on the right side.

- the font is wrong
- the icon is missing

<img width="527" alt="image" src="https://user-images.githubusercontent.com/33936661/207127338-63f6a5b0-fe03-4048-9c4b-fd847dbfc249.png">

Any suggestions?

Thanks a lot

**Comment by dferber90** [comment]
Hi, at that point I'd probably recommend using playwright to take the screenshots. It gets you much closer to the real thing and you won't be fighting jest all the time :P

I've written an article about this a while ago that might be useful https://frontend-digest.com/using-playwright-to-test-next-js-applications-80a767540091?sk=033775ad20645fa607c27d73c0dd561b. It's focused specifically on Next.js but might give you a good idea overall

**Comment by SaraRavasio** [comment]
Oh nice, thanks for the recommendation! I'll have a read! 🤗
