### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dferber90** [dferber90/jsdom-screenshot#5]
Hey @cancerberoSgx,

would you mind giving some feedback of what you're using this package for?

I've used it to experiment with Visual Regression Testing, but ultimately ended up using percy.io instead. They take care of differences in screenshots due to e.g. different font rendering on different machines. I kinda want to "warn" you that it can be a bit of a time-sink and inform that it's usually better to use a service for Visual Regression Testing instead.

Cheers

**Comment by cancerberoSgx** [comment]
hi!, I was just trying jest, enzyme and researching tools for visual regression testing. I like the way this can be integrated with jest and jest-image-snapshots (the API for markup and image snapshots is clean and consistent).

To be true, I don't have much experience on this area, don't know percy.io, but I liked this project together with jest and jest-image-snapshorts (KISS). 

BTW, I just pushed an update to latests on all dependencies. Will you maintain / take a look at this project ? I think your impl is clean and simple, but just wondering the situation since you are using another tool now ? 

THanks, keep it up!

**Comment by cancerberoSgx** [comment]
MY only doubt now is if it's worthwhile to keep using jsdom now that puppeteer is required, perhaps run all the tests just in puppeteer is cheaper/easier. What do you think ? I had some problems simulating events and other (expected) compatibly issues with jsdom and I wonder that, now that puppeteer is required, why can't I just run everything using puppeteer ? I would like your opinion? THanks!

**Comment by dferber90** [comment]
> To be true, I don't have much experience on this area, don't know percy.io, but I liked this project together with jest and jest-image-snapshorts (KISS).

Yeah this project was me experimenting with VRT because I wanted to be able to run visual-regression-tests alongside regular tests. The approach taken here doesn't "scale" to big teams very well, as
- you need to upload diff images when they fail on CI so people can see why they failed
- it's more convenient to be able to "approve" intended changes (when there was a diff which happened on purpose) by clicking a button on a web page than to rerun the tests manually

A bit more on this in: https://github.com/commercetools/ui-kit/pull/195#issuecomment-436651435

> MY only doubt now is if it's worthwhile to keep using jsdom now that puppeteer is required, perhaps run all the tests just in puppeteer is cheaper/easier

Yes, that's right. We took a similar approach in https://github.com/commercetools/ui-kit. We are not using `jsdom-screenshot` there, but we're using percy instead. You can check out our setup there. 

Here is a writeup of how we approach VRT, which has worked quite nicely for us: https://techblog.commercetools.com/keeping-a-react-design-system-consistent-f055160d5166

> I had some problems simulating events and other (expected) compatibly issues with jsdom

Yep, we also ran into some problems where we couldn't take screenshots of certain things (I vaguely remember virtualization in tables being a problem, not too sure though - it's been a while).


Thanks for your feedback 👍

**Comment by cancerberoSgx** [comment]
Thanks! nice feedback. Nevertheless, I would like to play a little bit more with this project, currently upgraded to puppeteer latest but still having an issue screenshot not taking style chage when I click my "switch to dark theme" button. Probably I will make another PR when I find the problem or perhaps richer `debug` option, if you don't mind :) THanks

**Comment by dferber90** [comment]
That could be because `enzyme`s `mount` doesn't rerender after you change stuff. I highly recommend using `react-testing-library` instead. There it should work as expected.

I switched to it a while ago after using `enzyme` extensively and never looked back. You can also use `react-testing-library`s `debug` option then, which is usually very helpful :P

**Comment by cancerberoSgx** [comment]
aja thanks for the tip,I can confirm is not a problem with this project since I'm dumping the HTML to a file and is incorrect... I thought it was a problem with old puppeteer but I just updated to latest but it's not. The html code generated from jsdom document's  is wrong somehow. thanks will do
